### ISSUE TITLE
How to uninstall ekanban?

### ISSUE THREAD

**Issue by freered-zz** [samchen2009/ekanban#64]
How to uninstall ekanban?  Thanks!
Environment:
  Redmine version                2.3.3.stable
  Ruby version                   1.9.3-p448 (2013-06-27) [x86_64-linux]
  Rails version                  3.2.13
  Environment                    production
  Database adapter               Mysql2
Redmine plugins:
  ekanban                        0.0.1
  redmine_backlogs               v1.0.5

**Comment by prmartinuk** [comment]
In a similar way to how you install it.
Open a command line terminal in the folder Redmine is installed in, and run:

```
rake redmine:plugins:migrate NAME=ekanban VERSION=0 RAILS_ENV=production
```

This will tidy up the database.
And then you can just remove the ekanban folder.

(N.B. make sure that you have the newest version of ekanban installed, because there was problems uninstalling some older versions).

**Comment by freered-zz** [comment]
Thank you so much for your response.
It is ok, thanks.
