### ISSUE TITLE
Not working on redmine 2.6.0

### ISSUE THREAD

**Issue by ghost** [samchen2009/ekanban#83]
As the title says...
I installed it on redmine 2.6 and it is not working.
- Project settings page is missing (404 error)
- Administration ekanban settings page is missing (404 error)

Too bad, cause it looks like a promising plugin!
I hope you find the time to make it work in newer versions of Redmin!
Good luck!

**Comment by gueux** [comment]
Hi, i've succesfully installed the Ekanban onto the Redmin 2.6.0
It has working Admin part and Show Kanbans pane into the project. 
But all of the panes are empty. No any ticket shows at the board. 

![kanban](https://cloud.githubusercontent.com/assets/10274175/5531969/4180a246-8a3a-11e4-9481-fd5bbbfe29d6.PNG)

Maybe you could point me with the way what I should check firstly? 
I am newly in Ruby but have a lot of time and intention in order to get Ekanban on Redmine.
Thanks.

**Comment by ghost** [comment]
Not using Redmine anymore

**Comment by asilverstein** [comment]
Please see my response to this issue for a possible solution: https://github.com/samchen2009/ekanban/issues/76
